-- MySQL Script generated by MySQL Workbench
-- Wed Apr  5 09:55:05 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Taller_0
-- -----------------------------------------------------
-- Se utilizara para generar los diagramas de entidad relacion para el taller 0. Asi como el codigo, hacviendo la claridad de que se estudio el tema y se entienden y manejan todos los comandos aquí usados.

-- -----------------------------------------------------
-- Schema Taller_0
--
-- Se utilizara para generar los diagramas de entidad relacion para el taller 0. Asi como el codigo, hacviendo la claridad de que se estudio el tema y se entienden y manejan todos los comandos aquí usados.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Taller_0` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `Taller_0` ;

-- -----------------------------------------------------
-- Table `Taller_0`.`Municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Taller_0`.`Municipio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `area` FLOAT NULL,
  `presupuesto` INT NULL,
  `gobernador` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `gobernador`
    FOREIGN KEY (`gobernador`)
    REFERENCES `Taller_0`.`Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nombre_UNIQUE` ON `Taller_0`.`Municipio` (`nombre` ASC) VISIBLE;

CREATE INDEX `gobernador_idx` ON `Taller_0`.`Municipio` (`gobernador` ASC) VISIBLE;

CREATE UNIQUE INDEX `gobernador_UNIQUE` ON `Taller_0`.`Municipio` (`gobernador` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Taller_0`.`Vivienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Taller_0`.`Vivienda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(45) NOT NULL,
  `capacidad` INT NOT NULL,
  `niveles` INT NOT NULL DEFAULT 1,
  `ubicacion` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `ubicacion`
    FOREIGN KEY (`ubicacion`)
    REFERENCES `Taller_0`.`Municipio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `Taller_0`.`Vivienda` (`id` ASC) VISIBLE;

CREATE INDEX `ubicacion_idx` ON `Taller_0`.`Vivienda` (`ubicacion` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Taller_0`.`Sexo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Taller_0`.`Sexo` (
  `id` INT NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `sexo_UNIQUE` ON `Taller_0`.`Sexo` (`sexo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Taller_0`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Taller_0`.`Persona` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL DEFAULT 'nn',
  `apellido` VARCHAR(45) NOT NULL DEFAULT 'nn',
  `edad` INT NOT NULL,
  `telefono` BIGINT(10) ZEROFILL NOT NULL DEFAULT 0,
  `sexo` INT NOT NULL DEFAULT 0,
  `vivienda` INT NULL,
  `cabeza_hogar` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `vivienda`
    FOREIGN KEY (`vivienda`)
    REFERENCES `Taller_0`.`Vivienda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cdh`
    FOREIGN KEY (`cabeza_hogar`)
    REFERENCES `Taller_0`.`Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sexo`
    FOREIGN KEY (`sexo`)
    REFERENCES `Taller_0`.`Sexo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `Taller_0`.`Persona` (`id` ASC) VISIBLE;

CREATE INDEX `vivienda_idx` ON `Taller_0`.`Persona` (`vivienda` ASC) VISIBLE;

CREATE INDEX `cdh_idx` ON `Taller_0`.`Persona` (`cabeza_hogar` ASC) VISIBLE;

CREATE INDEX `sexo_idx` ON `Taller_0`.`Persona` (`sexo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Taller_0`.`Propietario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Taller_0`.`Propietario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Persona_id` INT NOT NULL,
  `Vivienda_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Persona_has_Vivienda_Persona`
    FOREIGN KEY (`Persona_id`)
    REFERENCES `Taller_0`.`Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_has_Vivienda_Vivienda1`
    FOREIGN KEY (`Vivienda_id`)
    REFERENCES `Taller_0`.`Vivienda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Persona_has_Vivienda_Vivienda1_idx` ON `Taller_0`.`Propietario` (`Vivienda_id` ASC) VISIBLE;

CREATE INDEX `fk_Persona_has_Vivienda_Persona_idx` ON `Taller_0`.`Propietario` (`Persona_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
